### 1.0 Importing all the necessary libraries

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score ,f1_score
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report


## 2.0 Now, let us load the required data into individual variables

In [6]:
X_train=pd.read_csv("C:/Users/suman/OneDrive/Desktop/Surya/online_price_train_X.csv")
X_test = pd.read_csv("C:/Users/suman/OneDrive/Desktop/Surya/online_price_test_X.csv")
y_train = pd.read_csv("C:/Users/suman/OneDrive/Desktop/Surya/online_price_train_y.csv")
y_test = pd.read_csv("C:/Users/suman/OneDrive/Desktop/Surya/online_price_test_y.csv")

Let us create a data frame called performance and put all the needed metrics in it!

In [7]:
performance = pd.DataFrame({"model": [], "Accuracy": [], "Precision": [], "Recall": [], "F1": []})

# 2.1.1 Logistic Regression with Random Search

In [8]:
score_measure = "recall"
kfolds = 5

param_grid = {
    'penalty': ['None','l1','l2','elasticnet'],
    'solver':['saga','liblinear']
}

model = LogisticRegression()
rand_search = RandomizedSearchCV(estimator = model, param_distributions=param_grid, cv=kfolds, n_iter=500,
                           scoring=score_measure, verbose=1, n_jobs=-1, 
                           return_train_score=True)

_ = rand_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {rand_search.best_score_}")
print(f"... with parameters: {rand_search.best_params_}")

c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 8 is smaller than n_iter=500. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Fitting 5 folds for each of 8 candidates, totalling 40 fits
The best recall score is 0.8657534246575344
... with parameters: {'solver': 'liblinear', 'penalty': 'l1'}


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
20 fits failed out of a total of 40.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py", line 1160, in fit
    self._validate_params()
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "c:\

# 2.1.2 Logistic Regression with Grid Search

In [9]:
score_measure = "recall"
kfolds = 5
penalty = rand_search.best_params_['penalty']
solver = rand_search.best_params_['solver']

param_grid = {  
    'penalty': [penalty],
    'solver': [solver]
}

model = LogisticRegression()
grid_search = GridSearchCV(estimator = model, param_grid=param_grid, cv=kfolds, 
                           scoring=score_measure, verbose=1, n_jobs=-1,
                           return_train_score=True)

_ = grid_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {grid_search.best_score_}")
print(f"... with parameters: {grid_search.best_params_}")

bestRecallLogistic = grid_search.best_estimator_

Fitting 5 folds for each of 1 candidates, totalling 5 fits
The best recall score is 0.8657534246575344
... with parameters: {'penalty': 'l1', 'solver': 'liblinear'}


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [10]:
c_matrix = confusion_matrix(y_test, grid_search.predict(X_test))
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"Logistic Regression",
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])
performance

model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.905537   0.902208  0.913738  0.907937

## 2.2.1 SVM (Linear) - Random Search

In [11]:
score_measure = "recall"
kfolds = 2

param_grid = {
    'C': np.arange(1,20),   
    'gamma': ['scale','auto'],
    'kernel':['linear']
}

model = SVC()
rand_search = RandomizedSearchCV(estimator = model, param_distributions=param_grid, cv=kfolds, n_iter=50,
                           scoring=score_measure, verbose=1, n_jobs=-1, 
                           return_train_score=True)

_ = rand_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {rand_search.best_score_}")
print(f"... with parameters: {rand_search.best_params_}")

Fitting 2 folds for each of 38 candidates, totalling 76 fits


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 38 is smaller than n_iter=50. Running 38 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


The best recall score is 0.8684931506849315
... with parameters: {'kernel': 'linear', 'gamma': 'scale', 'C': 3}


## 2.2.2 SVM (Linear) - Grid Search

In [12]:
score_measure = "recall"
kfolds = 5

C = rand_search.best_params_['C']
gamma = rand_search.best_params_['gamma']
kernel = rand_search.best_params_['kernel']

param_grid = {
    'C': np.arange(C-3,C+3),  
    'gamma': [gamma],
    'kernel': [kernel]
    
}

model = SVC()
grid_search = GridSearchCV(estimator = model, param_grid=param_grid, cv=kfolds, 
                           scoring=score_measure, verbose=1, n_jobs=-1,
                           return_train_score=True)

_ = grid_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {grid_search.best_score_}")
print(f"... with parameters: {grid_search.best_params_}")

bestRecallSVM_linear = grid_search.best_estimator_

Fitting 5 folds for each of 6 candidates, totalling 30 fits
The best recall score is 0.8671232876712329
... with parameters: {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
5 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\svm\_base.py", line 180, in fit
    self._validate_params()
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\suman\ana

In [13]:
c_matrix = confusion_matrix(y_test, grid_search.predict(X_test))
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"SVM-Linear", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])
performance

model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.905537   0.902208  0.913738  0.907937
0           SVM-Linear  0.920195   0.945946  0.894569  0.919540

## 2.3.1 SVM (RBF) - Random Search

In [14]:
score_measure = "recall"
kfolds = 2

param_grid = {
    'C': np.arange(1,20),   
    'gamma': ['scale','auto'],
    'kernel':['rbf']
}

model = SVC()
rand_search = RandomizedSearchCV(estimator = model, param_distributions=param_grid, cv=kfolds, n_iter=50,
                           scoring=score_measure, verbose=1, n_jobs=-1, 
                           return_train_score=True)

_ = rand_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {rand_search.best_score_}")
print(f"... with parameters: {rand_search.best_params_}")

Fitting 2 folds for each of 38 candidates, totalling 76 fits


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 38 is smaller than n_iter=50. Running 38 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


The best recall score is 0.8931506849315068
... with parameters: {'kernel': 'rbf', 'gamma': 'auto', 'C': 18}


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## 2.3.2 SVM (RBF) - Grid Search

In [15]:
score_measure = "recall"
kfolds = 5

C = rand_search.best_params_['C']
gamma = rand_search.best_params_['gamma']
kernel = rand_search.best_params_['kernel']

param_grid = {
    'C': np.arange(C-3,C+3),  
    'gamma': [gamma],
    'kernel': [kernel]
    
}

model = SVC()
grid_search = GridSearchCV(estimator = model, param_grid=param_grid, cv=kfolds, 
                           scoring=score_measure, verbose=1, n_jobs=-1,
                           return_train_score=True)

_ = grid_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {grid_search.best_score_}")
print(f"... with parameters: {grid_search.best_params_}")

bestRecallSVM_rbf = grid_search.best_estimator_

Fitting 5 folds for each of 6 candidates, totalling 30 fits
The best recall score is 0.9095890410958904
... with parameters: {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [16]:
c_matrix = confusion_matrix(y_test, grid_search.predict(X_test))
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"SVM-RBF", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])
performance

model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.905537   0.902208  0.913738  0.907937
0           SVM-Linear  0.920195   0.945946  0.894569  0.919540
0              SVM-RBF  0.903909   0.891975  0.923323  0.907378

## 2.4.1 SVM (Poly) - Random Search

In [17]:
score_measure = "recall"
kfolds = 2

param_grid = {
    'gamma':[1e-2, 1e-3, 1e-4, 1e-5],
    'C':[0.001, 0.10, 0.0001,0.00001],
    'kernel':['poly']
}

model = SVC()
rand_search = RandomizedSearchCV(estimator = model, param_distributions=param_grid, cv=kfolds, n_iter=10,
                           scoring=score_measure, verbose=1, n_jobs=-1, 
                           return_train_score=True)

_ = rand_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {rand_search.best_score_}")
print(f"... with parameters: {rand_search.best_params_}")

Fitting 2 folds for each of 10 candidates, totalling 20 fits


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


The best recall score is 0.8671232876712329
... with parameters: {'kernel': 'poly', 'gamma': 0.001, 'C': 0.1}


## 2.4.2 SVM (Poly) - Grid Search

In [18]:
score_measure = "recall"
kfolds = 5

C = rand_search.best_params_['C']
gamma = rand_search.best_params_['gamma']
kernel = rand_search.best_params_['kernel']

param_grid = {
    'C': np.arange(C-3,C+3),  
    'gamma': [gamma],
    'kernel': [kernel]
    
}

model = SVC()
grid_search = GridSearchCV(estimator = model, param_grid=param_grid, cv=kfolds, 
                           scoring=score_measure, verbose=1, n_jobs=-1,
                           return_train_score=True)

_ = grid_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {grid_search.best_score_}")
print(f"... with parameters: {grid_search.best_params_}")

bestRecallSVM_poly = grid_search.best_estimator_

Fitting 5 folds for each of 6 candidates, totalling 30 fits


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\svm\_base.py", line 180, in fit
    self._validate_params()
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\suman\an

The best recall score is 0.8712328767123287
... with parameters: {'C': 0.10000000000000009, 'gamma': 0.001, 'kernel': 'poly'}


In [19]:
c_matrix = confusion_matrix(y_test, grid_search.predict(X_test))
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"SVM-Poly", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])
performance

model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.905537   0.902208  0.913738  0.907937
0           SVM-Linear  0.920195   0.945946  0.894569  0.919540
0              SVM-RBF  0.903909   0.891975  0.923323  0.907378
0             SVM-Poly  0.915309   0.930693  0.900958  0.915584

## 2.5.1 Decision Trees - Random Search 

In [20]:
score_measure = "recall"
kfolds = 5

param_grid = {
    'min_samples_split': np.arange(2,100),  
    'min_samples_leaf': np.arange(1,75),
    'min_impurity_decrease': np.arange(0.0001, 0.01, 0.0005),
    'max_leaf_nodes': np.arange(5, 80), 
    'max_depth': np.arange(1,40), 
    'criterion': ['entropy', 'gini'],
}

model = DecisionTreeClassifier()
rand_search = RandomizedSearchCV(estimator = model, param_distributions=param_grid, cv=kfolds, n_iter=500,
                           scoring=score_measure, verbose=1, n_jobs=-1, 
                           return_train_score=True)

_ = rand_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {rand_search.best_score_}")
print(f"... with parameters: {rand_search.best_params_}")

Fitting 5 folds for each of 500 candidates, totalling 2500 fits
The best recall score is 0.9150684931506848
... with parameters: {'min_samples_split': 23, 'min_samples_leaf': 11, 'min_impurity_decrease': 0.0001, 'max_leaf_nodes': 68, 'max_depth': 25, 'criterion': 'gini'}


## 2.5.2 DECISION TREE - GRID SEARCH

In [21]:
score_measure = "recall"
kfolds = 5
min_samples_split = rand_search.best_params_['min_samples_split']
min_samples_leaf = rand_search.best_params_['min_samples_leaf']
min_impurity_decrease = rand_search.best_params_['min_impurity_decrease']
max_leaf_nodes = rand_search.best_params_['max_leaf_nodes']
max_depth = rand_search.best_params_['max_depth']
criterion = rand_search.best_params_['criterion']

param_grid = {
    'min_samples_split': np.arange(min_samples_split-2,min_samples_split+2),  
    'min_samples_leaf': np.arange(min_samples_leaf-2,min_samples_leaf+2),
    'min_impurity_decrease': np.arange(min_impurity_decrease-0.0001, min_impurity_decrease+0.0001, 0.00005),
    'max_leaf_nodes': np.arange(max_leaf_nodes-2,max_leaf_nodes+2), 
    'max_depth': np.arange(max_depth-2,max_depth+2), 
    'criterion': [criterion]
}

model = DecisionTreeClassifier()
grid_search = GridSearchCV(estimator = model, param_grid=param_grid, cv=kfolds, 
                           scoring=score_measure, verbose=1, n_jobs=-1,
                           return_train_score=True)

_ = grid_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {grid_search.best_score_}")
print(f"... with parameters: {grid_search.best_params_}")

bestRecallDTree = grid_search.best_estimator_

Fitting 5 folds for each of 1024 candidates, totalling 5120 fits
The best recall score is 0.9232876712328768
... with parameters: {'criterion': 'gini', 'max_depth': 23, 'max_leaf_nodes': 66, 'min_impurity_decrease': 5e-05, 'min_samples_leaf': 9, 'min_samples_split': 22}


In [22]:
c_matrix = confusion_matrix(y_test, grid_search.predict(X_test))
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"Decision Tree", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

## 2.6 Neural Networks

In [23]:
%%time

ann = MLPClassifier(hidden_layer_sizes=(60,50,40), solver='adam', max_iter=200)
_ = ann.fit(X_train, y_train)

c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


CPU times: total: 1.56 s
Wall time: 512 ms


In [24]:
%%time
y_pred = ann.predict(X_test)

CPU times: total: 15.6 ms
Wall time: 4.75 ms


In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      1.00      0.84       301
           1       1.00      0.65      0.78       313

    accuracy                           0.82       614
   macro avg       0.86      0.82      0.81       614
weighted avg       0.87      0.82      0.81       614



## 2.6.1 Neural Networks With RandomizedSearchCV

In [28]:
%%time

score_measure = "accuracy"
kfolds = 5

param_grid = {
    'hidden_layer_sizes': [ (50,), (70,),(50,30), (40,20), (60,40, 20), (70,50,40)],
    'activation': ['logistic', 'tanh', 'relu'],
    'solver': ['adam', 'sgd'],
    'alpha': [0, .2, .5, .7, 1],
    'learning_rate': ['constant', 'invscaling', 'adaptive'],
    'learning_rate_init': [0.001, 0.01, 0.1, 0.2, 0.5],
    'max_iter': [5000]
}

ann = MLPClassifier()
grid_search = RandomizedSearchCV(estimator = ann, param_distributions=param_grid, cv=kfolds, n_iter=100,
                           scoring=score_measure, verbose=1, n_jobs=-1,  # n_jobs=-1 will utilize all available CPUs 
                           return_train_score=True)

_ = grid_search.fit(X_train, y_train)

bestRecallTree = grid_search.best_estimator_

print(grid_search.best_params_)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'solver': 'adam', 'max_iter': 5000, 'learning_rate_init': 0.001, 'learning_rate': 'adaptive', 'hidden_layer_sizes': (50, 30), 'alpha': 1, 'activation': 'tanh'}
CPU times: total: 3.66 s
Wall time: 39.6 s


In [29]:
%%time
y_pred = bestRecallTree.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.88      0.89       301
           1       0.89      0.92      0.90       313

    accuracy                           0.90       614
   macro avg       0.90      0.90      0.90       614
weighted avg       0.90      0.90      0.90       614

CPU times: total: 31.2 ms
Wall time: 20.6 ms


## 2.6.2 Neural Networks With GridSearchCV

In [30]:
%%time

score_measure = "accuracy"
kfolds = 5

param_grid = {
    'hidden_layer_sizes': [ (30,), (50,), (70,), (90,)],
    'activation': ['tanh', 'relu'],
    'solver': ['adam'],
    'alpha': [.5, .7, 1],
    'learning_rate': ['adaptive', 'invscaling'],
    'learning_rate_init': [0.005, 0.01, 0.15],
    'max_iter': [5000]
}

ann = MLPClassifier()
grid_search = GridSearchCV(estimator = ann, param_grid=param_grid, cv=kfolds, 
                           scoring=score_measure, verbose=1, n_jobs=-1,  # n_jobs=-1 will utilize all available CPUs 
                           return_train_score=True)

_ = grid_search.fit(X_train, y_train)

bestRecallTree = grid_search.best_estimator_

print(grid_search.best_params_)

Fitting 5 folds for each of 144 candidates, totalling 720 fits


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'activation': 'tanh', 'alpha': 0.5, 'hidden_layer_sizes': (70,), 'learning_rate': 'adaptive', 'learning_rate_init': 0.005, 'max_iter': 5000, 'solver': 'adam'}
CPU times: total: 3.38 s
Wall time: 1min 1s


In [31]:
%%time
y_pred = bestRecallTree.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.74      1.00      0.85       301
           1       1.00      0.65      0.79       313

    accuracy                           0.82       614
   macro avg       0.87      0.83      0.82       614
weighted avg       0.87      0.82      0.82       614

CPU times: total: 31.2 ms
Wall time: 21.3 ms


In [32]:
performance

model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.905537   0.902208  0.913738  0.907937
0           SVM-Linear  0.920195   0.945946  0.894569  0.919540
0              SVM-RBF  0.903909   0.891975  0.923323  0.907378
0             SVM-Poly  0.915309   0.930693  0.900958  0.915584
0        Decision Tree  0.926710   0.911043  0.948882  0.929577

## 2.7.1 MLP Classifier

In [33]:
%%time

model1 = MLPClassifier(
    hidden_layer_sizes=(60,50,40), 
    activation = 'relu',
    solver='adam',
    alpha=0.0001, # Strength of the L2 regularization term
    batch_size='auto',
    learning_rate = 'constant',
    learning_rate_init = 0.001,
    max_iter=200,
    tol=0.00001, 
    early_stopping = True,
    n_iter_no_change = 5,
    verbose=True
    
)
_ = model1.fit(X_train, y_train)

# Currently (version 1.2.2), MLPClassifier supports only the Cross-Entropy loss function.
# https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html

c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 11.35123364
Validation score: 0.493151
Iteration 2, loss = 7.49112559
Validation score: 0.500000
Iteration 3, loss = 8.82611173
Validation score: 0.500000
Iteration 4, loss = 6.14701907
Validation score: 0.500000
Iteration 5, loss = 5.33649017
Validation score: 0.500000
Iteration 6, loss = 4.26366312
Validation score: 0.500000
Iteration 7, loss = 3.28785917
Validation score: 0.589041
Iteration 8, loss = 1.81747140
Validation score: 0.513699
Iteration 9, loss = 1.63405129
Validation score: 0.582192
Iteration 10, loss = 0.99550739
Validation score: 0.541096
Iteration 11, loss = 0.84324448
Validation score: 0.609589
Iteration 12, loss = 0.68974206
Validation score: 0.684932
Iteration 13, loss = 0.62973180
Validation score: 0.698630
Iteration 14, loss = 0.58218369
Validation score: 0.684932
Iteration 15, loss = 0.53773005
Validation score: 0.636986
Iteration 16, loss = 0.61287094
Validation score: 0.678082
Iteration 17, loss = 0.56808793
Validation score: 0.657534
Itera

In [34]:
model1.loss_curve_

[11.35123363876668,
 7.491125594164363,
 8.826111731490588,
 6.14701907217089,
 5.336490166374211,
 4.263663121678422,
 3.287859165245858,
 1.8174714002752275,
 1.6340512852206226,
 0.9955073943485522,
 0.8432444784895147,
 0.6897420579156748,
 0.6297317991003879,
 0.5821836913139338,
 0.5377300490520339,
 0.6128709393975389,
 0.5680879275254829,
 0.5854260899293794,
 0.4816764918334295,
 0.49936591975199024,
 0.4317268279150596,
 0.39683001214698777,
 0.38825421661873943,
 0.4425426923755952,
 0.40051663626810424,
 0.34485843375019304,
 0.38530107965388355,
 0.6580971492866534,
 0.5419980968100468,
 0.5084042991217271,
 0.4215824143713198,
 0.47100850793731047,
 0.3808489850724948,
 0.30446779651675515,
 0.32046464165393795]

In [35]:
%%time
y_pred = model1.predict(X_test)

CPU times: total: 0 ns
Wall time: 12.3 ms


In [36]:
print(classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.828     0.977     0.896       301
           1      0.973     0.805     0.881       313

    accuracy                          0.889       614
   macro avg      0.901     0.891     0.889       614
weighted avg      0.902     0.889     0.889       614



In [37]:
y_pred = model1.predict(X_test)
y_pred

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,

## 2.7.2 MLP Classifier with RandomSearchCV

In [38]:
%%time

param_distributions = {
    'hidden_layer_sizes': [ (64,), (128,),(128,64), (64,128), (64,128,196), (196,128,64)],
    'activation': ['logistic', 'tanh', 'relu'],
    'solver': ['adam', 'sgd'],
    'alpha': [0, .0001, .0005, .001, .005],
    'batch_size': [25, 50, 100],
    'learning_rate': ['constant', 'invscaling', 'adaptive'],
    'learning_rate_init': [0.0005, 0.001, 0.005, 0.01],
    'max_iter': [5000],
    'tol': [0.000005, 0.00001, 0.00005],
    'early_stopping':[True],
    'n_iter_no_change':[5],
}

random_search = RandomizedSearchCV(
    estimator = MLPClassifier(), # a blank slate... RandomizedSearchCV will send parameters.
    param_distributions=param_distributions, 
    cv=3, 
    n_iter=300,
    scoring='accuracy', # note that we could also choose any other scoring metric that is appropriate for a multi-class problem - such as f1_macro, f1_micro, f1_weighted, etc.
    verbose=1, 
    n_jobs=-1,  # n_jobs=-1 will utilize all available CPUs 
    return_train_score=True
)

_ = random_search.fit(X_train, y_train)

Fitting 3 folds for each of 300 candidates, totalling 900 fits


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


CPU times: total: 4.62 s
Wall time: 1min 19s


In [39]:
model2 = random_search.best_estimator_

print(random_search.best_params_)

{'tol': 1e-05, 'solver': 'adam', 'n_iter_no_change': 5, 'max_iter': 5000, 'learning_rate_init': 0.001, 'learning_rate': 'adaptive', 'hidden_layer_sizes': (64,), 'early_stopping': True, 'batch_size': 25, 'alpha': 0.0001, 'activation': 'relu'}


In [54]:
%%time
y_pred = model2.predict(X_test)

print(classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.911     0.917     0.914       301
           1      0.920     0.914     0.917       313

    accuracy                          0.915       614
   macro avg      0.915     0.915     0.915       614
weighted avg      0.915     0.915     0.915       614

CPU times: total: 15.6 ms
Wall time: 19.1 ms


## 2.8.1 Keras

In [41]:
import tensorflow as tf
from tensorflow import keras

# fix random seed for reproducibility
np.random.seed(1)
tf.random.set_seed(1)

In [42]:
%%time

def build_clf(meta, hidden_layer_sizes, dropout):
    n_features_in_ = meta["n_features_in_"]
    n_classes_ = meta["n_classes_"]
    target_encoder_ = meta["target_encoder_"]
    
    model = tf.keras.models.Sequential()
    model.add(keras.layers.Input(shape=n_features_in_)),
    #for hidden_layer_size in hidden_layer_sizes:
    for hidden_layer_size in hidden_layer_sizes:
        model.add(keras.layers.Dense(hidden_layer_size, 
            kernel_initializer= tf.keras.initializers.GlorotUniform(), 
            bias_initializer=keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=None), 
            activation="relu"))
        model.add(keras.layers.Dropout(dropout))
    model.add(tf.keras.layers.Dense(10, activation='softmax'))
    
    #though you could return a compiled model, it's not necessary, and would result in the loss of these
    # parameters in the tune process - as they would be 'hard coded'
    # model.compile(loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) 

    return model

CPU times: total: 0 ns
Wall time: 0 ns


In [43]:
%%time

# If you don't have the following installed, from command line '!pip install scikeras'
from scikeras.wrappers import KerasClassifier

keras_clf = KerasClassifier(
    model=build_clf,
    hidden_layer_sizes=64,
    dropout=0.5,
    optimizer=keras.optimizers.Adam,
    optimizer__learning_rate=0.0001
)
keras_clf.get_params()

CPU times: total: 15.6 ms
Wall time: 32.9 ms


{'model': <function __main__.build_clf(meta, hidden_layer_sizes, dropout)>,
 'build_fn': None,
 'warm_start': False,
 'random_state': None,
 'optimizer': keras.optimizers.optimizer_v2.adam.Adam,
 'loss': None,
 'metrics': None,
 'batch_size': None,
 'validation_batch_size': None,
 'verbose': 1,
 'callbacks': None,
 'validation_split': 0.0,
 'shuffle': True,
 'run_eagerly': False,
 'epochs': 1,
 'hidden_layer_sizes': 64,
 'dropout': 0.5,
 'optimizer__learning_rate': 0.0001,
 'class_weight': None}

In [44]:
%%time

params = {
    
    # the following are model parameters, and therefore must be defined as parameters in the KarasClassifier, and then in the build_clf function
    'model__hidden_layer_sizes': [(70,),(90, ), (100,), (100, 90)], # this will require KarasClassifier and build_clf to have hidden_layer_sizes parameter set
    'model__dropout': [0, 0.1], # this will require KarasClassifier and build_clf to have hidden_layer_sizes parameter set
    
    # the following are 'fit' parameters, the scikeras wrapper provides these parameters. These are passed to the 'model.fit' method for each fit of the model
    'batch_size':[20, 60, 100],
    'epochs':[10],
    'optimizer':['adam','sgd'],
    'loss':['sparse_categorical_crossentropy'],
    
    # this is added to the optimizer 
    'optimizer__learning_rate': [0.0001, 0.001, 0.01]

}
keras_clf.get_params()

CPU times: total: 0 ns
Wall time: 0 ns


{'model': <function __main__.build_clf(meta, hidden_layer_sizes, dropout)>,
 'build_fn': None,
 'warm_start': False,
 'random_state': None,
 'optimizer': keras.optimizers.optimizer_v2.adam.Adam,
 'loss': None,
 'metrics': None,
 'batch_size': None,
 'validation_batch_size': None,
 'verbose': 1,
 'callbacks': None,
 'validation_split': 0.0,
 'shuffle': True,
 'run_eagerly': False,
 'epochs': 1,
 'hidden_layer_sizes': 64,
 'dropout': 0.5,
 'optimizer__learning_rate': 0.0001,
 'class_weight': None}

## 2.8.2 Keras with RandomSearchCV

In [46]:
%%time

from sklearn.model_selection import RandomizedSearchCV
#from tensorflow.keras.callbacks import EarlyStopping

rnd_search_cv = RandomizedSearchCV(
    estimator=keras_clf, 
    param_distributions=params, 
    scoring='accuracy',  # we could use any appropriate sklearn metric here (i.e. accuracy, f1_micro, f1_macro)
    n_iter=50, 
    cv=3)

# In rare cases, you may find your model training results in exceeding python's default recursion limit.
# If needed, you can increase this excersion limit by using the following code.
#import sys
#sys.setrecursionlimit(10000) # note: the default is 3000 (python 3.9)

_ = rnd_search_cv.fit(X_train, y_train,  verbose=1)

# You can create 'call back' functions. These are functions that will be called at the 
# end of each epoch. There are a number of builtin functions created for this purpose, 
# one of which is EarlyStopping -- that, based on the parameters you give, will stop
# the training process. This is useful when the algorithm is not making any significant
# gains through further training. 
#earlystop = EarlyStopping(monitor='val_loss', patience=5, verbose=0, mode='auto')
#callback = [earlystop]
#_ = rnd_search_cv.fit(X_train, y_train, callbacks=callback, verbose=0)

Epoch 1/10
10/10 [==============================] - 0s 3ms/step - loss: 140.3801
Epoch 2/10
10/10 [==============================] - 0s 5ms/step - loss: 121.7119
Epoch 3/10
10/10 [==============================] - 0s 4ms/step - loss: 91.2213
Epoch 4/10
10/10 [==============================] - 0s 4ms/step - loss: 83.2160
Epoch 5/10
10/10 [==============================] - 0s 4ms/step - loss: 56.6035
Epoch 6/10
10/10 [==============================] - 0s 4ms/step - loss: 50.1205
Epoch 7/10
10/10 [==============================] - 0s 4ms/step - loss: 36.9521
Epoch 8/10
10/10 [==============================] - 0s 4ms/step - loss: 32.2779
Epoch 9/10
10/10 [==============================] - 0s 4ms/step - loss: 28.7153
Epoch 10/10
5/5 [==============================] - 0s 2ms/step
Epoch 1/10
10/10 [==============================] - 0s 3ms/step - loss: 202.1717
Epoch 2/10
10/10 [==============================] - 0s 4ms/step - loss: 143.4026
Epoch 3/10
10/10 [==============================] - 0

c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 234, in __call__
    return self._score(
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 276, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\scikeras\wrappers.py", line 1054, in predict
    y_pred = self.

10/10 [==============================] - 0s 2ms/step - loss: 301.7791
Epoch 2/10
10/10 [==============================] - 0s 3ms/step - loss: 254.4754
Epoch 3/10
10/10 [==============================] - 0s 4ms/step - loss: 207.3729
Epoch 4/10
10/10 [==============================] - 0s 3ms/step - loss: 160.2429
Epoch 5/10
10/10 [==============================] - 0s 2ms/step - loss: 113.0946
Epoch 6/10
10/10 [==============================] - 0s 3ms/step - loss: 71.2835
Epoch 7/10
10/10 [==============================] - 0s 3ms/step - loss: 55.6595
Epoch 8/10
10/10 [==============================] - 0s 3ms/step - loss: 36.9990
Epoch 9/10
10/10 [==============================] - 0s 3ms/step - loss: 20.1314
Epoch 10/10
5/5 [==============================] - 0s 2ms/step
Epoch 1/10
10/10 [==============================] - 0s 3ms/step - loss: 209.8043
Epoch 2/10
10/10 [==============================] - 0s 4ms/step - loss: 173.7078
Epoch 3/10
10/10 [==============================] - 0s 3ms/st

c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 234, in __call__
    return self._score(
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 276, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\scikeras\wrappers.py", line 1054, in predict
    y_pred = self.

10/10 [==============================] - 0s 2ms/step - loss: 715.1686
Epoch 2/10
10/10 [==============================] - 0s 4ms/step - loss: 693.1362
Epoch 3/10
10/10 [==============================] - 0s 3ms/step - loss: 675.8328
Epoch 4/10
10/10 [==============================] - 0s 3ms/step - loss: 658.4986
Epoch 5/10
10/10 [==============================] - 0s 3ms/step - loss: 637.1302
Epoch 6/10
10/10 [==============================] - 0s 4ms/step - loss: 619.6465
Epoch 7/10
10/10 [==============================] - 0s 4ms/step - loss: 605.3041
Epoch 8/10
10/10 [==============================] - 0s 3ms/step - loss: 584.7579
Epoch 9/10
10/10 [==============================] - 0s 3ms/step - loss: 562.8077
Epoch 10/10
5/5 [==============================] - 0s 2ms/step
Epoch 1/10
10/10 [==============================] - 0s 2ms/step - loss: 73.8131
Epoch 2/10
10/10 [==============================] - 0s 3ms/step - loss: 28.2924
Epoch 3/10
10/10 [==============================] - 0s 3ms/

c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 234, in __call__
    return self._score(
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 276, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\scikeras\wrappers.py", line 1054, in predict
    y_pred = self.

10/10 [==============================] - 0s 3ms/step - loss: 470.0782
Epoch 2/10
10/10 [==============================] - 0s 4ms/step - loss: 438.1730
Epoch 3/10
10/10 [==============================] - 0s 3ms/step - loss: 400.6724
Epoch 4/10
10/10 [==============================] - 0s 3ms/step - loss: 373.6652
Epoch 5/10
10/10 [==============================] - 0s 3ms/step - loss: 339.1690
Epoch 6/10
10/10 [==============================] - 0s 4ms/step - loss: 309.4514
Epoch 7/10
10/10 [==============================] - 0s 4ms/step - loss: 284.7029
Epoch 8/10
10/10 [==============================] - 0s 3ms/step - loss: 250.5402
Epoch 9/10
10/10 [==============================] - 0s 4ms/step - loss: 223.9139
Epoch 10/10
5/5 [==============================] - 0s 0s/step
Epoch 1/10


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 234, in __call__
    return self._score(
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 276, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\scikeras\wrappers.py", line 1054, in predict
    y_pred = self.

10/10 [==============================] - 0s 3ms/step - loss: 834.9404
Epoch 2/10
10/10 [==============================] - 0s 4ms/step - loss: 793.4894
Epoch 3/10
10/10 [==============================] - 0s 3ms/step - loss: 749.0915
Epoch 4/10
10/10 [==============================] - 0s 3ms/step - loss: 688.1240
Epoch 5/10
10/10 [==============================] - 0s 3ms/step - loss: 656.0274
Epoch 6/10
10/10 [==============================] - 0s 4ms/step - loss: 610.0636
Epoch 7/10
10/10 [==============================] - 0s 4ms/step - loss: 553.9738
Epoch 8/10
10/10 [==============================] - 0s 3ms/step - loss: 507.4230
Epoch 9/10
10/10 [==============================] - 0s 4ms/step - loss: 458.1970
Epoch 10/10
5/5 [==============================] - 0s 2ms/step
Epoch 1/10


c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 234, in __call__
    return self._score(
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 276, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\suman\anaconda3\envs\tf\lib\site-packages\scikeras\wrappers.py", line 1054, in predict
    y_pred = self.

17/17 [==============================] - 0s 3ms/step - loss: 16830734.0000
Epoch 2/10
17/17 [==============================] - 0s 3ms/step - loss: 1.1572
Epoch 3/10
17/17 [==============================] - 0s 3ms/step - loss: 0.9480
Epoch 4/10
17/17 [==============================] - 0s 2ms/step - loss: 0.8630
Epoch 5/10
17/17 [==============================] - 0s 3ms/step - loss: 0.8178
Epoch 6/10
17/17 [==============================] - 0s 3ms/step - loss: 0.7916
Epoch 7/10
17/17 [==============================] - 0s 3ms/step - loss: 0.7730
Epoch 8/10
17/17 [==============================] - 0s 3ms/step - loss: 0.7608
Epoch 9/10
17/17 [==============================] - 0s 3ms/step - loss: 0.7524
Epoch 10/10
9/9 [==============================] - 0s 2ms/step
Epoch 1/10
17/17 [==============================] - 0s 2ms/step - loss: 40090896.0000
Epoch 2/10
17/17 [==============================] - 0s 3ms/step - loss: 1.2139
Epoch 3/10
17/17 [==============================] - 0s 3ms/step -

c:\Users\suman\anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.50068446 0.49931554 0.74870642 0.59240246 0.69855474 0.79594843
 0.57460643 0.49931554 0.50068446 0.5        0.71365095 0.49931554
 0.49931554 0.69772944 0.49931554 0.49931554        nan        nan
 0.71850838 0.54595195 0.68617385 0.76705171 0.54866586 0.49931554
 0.49931554 0.68959898 0.51440188 0.50068446 0.734282   0.46723874
 0.68206708 0.5549063  0.50068446 0.81571476 0.69166082 0.49931413
        nan 0.5        0.69866882 0.49931554 0.49931554 0.49931554
 0.51368925 0.5        0.85547134 0.50068446 0.53909324 0.49931554
 0.5        0.5       ]
  warnings.warn(


15/15 [==============================] - 0s 5ms/step - loss: 71.5150
Epoch 2/10
15/15 [==============================] - 0s 3ms/step - loss: 42.1546
Epoch 3/10
15/15 [==============================] - 0s 3ms/step - loss: 30.3899
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 22.2704
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 11.6875
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 7.1034
Epoch 7/10
15/15 [==============================] - 0s 3ms/step - loss: 4.5780
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 2.5456
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 2.0592
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 1.8238
CPU times: total: 17min 38s
Wall time: 2min 56s


In [48]:
rnd_search_cv.best_params_

{'optimizer__learning_rate': 0.01,
 'optimizer': 'adam',
 'model__hidden_layer_sizes': (100,),
 'model__dropout': 0.1,
 'loss': 'sparse_categorical_crossentropy',
 'epochs': 10,
 'batch_size': 100}

In [49]:
best_model = rnd_search_cv.best_estimator_

In [53]:
from sklearn.metrics import classification_report

print(classification_report(y_test, best_model.predict(X_test), digits=3))

7/7 [==============================] - 0s 4ms/step
              precision    recall  f1-score   support

           0      0.681     1.000     0.810       301
           1      1.000     0.550     0.709       313

    accuracy                          0.770       614
   macro avg      0.840     0.775     0.760       614
weighted avg      0.844     0.770     0.759       614



# 3.0 ANALYSIS

Here, we can see that the Decision Trees have the best recall score of all the models that we have tried. We achieved a sore of 95.52 using decision trees.

The Next best metric we have is SupportVectorMachine using RBF Kernel. But let us go with Decision Trees as we have better score there in addition to the fact that Decision Trees deal with colinear data in a better way

Also, if we look at the recall scores of the NeuralNets, they are 86 with RandomSearchCv and 67 with GridSearch. We have The Decision Trees performing better than thge neuralnets in this case.

Our Final goal is to achieve the best recall score so that we can reduce False Negatives as much as we can. Theoretically, we can achieve a recall score upto 1 and in reality, we achieved it upto 0.955. So, we have dealt with the issue in the best possible way we can and reduced the occurances of false negatives.

## MLPs and Keras Summary

And, We have Neural Networks using MLPClassifier and Keras and the outputs are here to see.

* MLP Classifier has a recall value of 80.5
* MLP Classifier with RandomisedSearchCV has a recall value of 91.4
* Keras achieved a recall value of 55

The reason for Decision trees out-performing these ML Models is because DecisionTrees explicitly fit the parameters into the model to manage the flow of inputs where-as NeuralNets with MLPs and Keras fit parameters to transform the input and indirectly direct the activations of following neurons.