# AirBNB Data Preparation where target is price_gte_150


## 1.0 Setup


In [1]:
# import numpy and pandas libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
# set random seed to ensure that results are repeatable
np.random.seed(1)

## 2.0 Load data 

In [2]:
# load data
airbnb = pd.read_csv("C:/Users/surya/OneDrive/Documents/USF/Classes/Semester-2/DSP/Week-4 Codes/airbnb.csv")

airbnb.head(5)

host_is_superhost  host_identity_verified neighbourhood_cleansed  \
0                  0                       0             Roslindale   
1                  0                       1             Roslindale   
2                  1                       1             Roslindale   
3                  0                       0             Roslindale   
4                  1                       1             Roslindale   

    latitude  longitude property_type        room_type  accommodates  \
0  42.282619 -71.133068         House  Entire home/apt             4   
1  42.286241 -71.134374     Apartment     Private room             2   
2  42.292438 -71.135765     Apartment     Private room             2   
3  42.281106 -71.121021         House     Private room             4   
4  42.284512 -71.136258         House     Private room             2   

   bathrooms  bedrooms  ...  guests_included price_per_extra_person  \
0        1.5       2.0  ...                1                      0   
1        1.0       1.0  ...                0                      0   
2        1.0       1.0  ...                1                     20   
3        1.0       1.0  ...                2                     25   
4        1.5       1.0  ...                1                      0   

   minimum_nights  number_of_reviews  number_days_btw_first_last_review  \
0               2                  0                                  0   
1               2                 36                                804   
2               3                 41                               2574   
3               1                  1                                  0   
4               2                 29                                380   

   review_scores_rating  cancellation_policy  price  price_gte_150  \
0                   NaN             moderate    250              1   
1                  94.0             moderate     65              0   
2                  98.0             moderate     65              0   
3                 100.0             moderate     75              0   
4                  99.0             flexible     79              0   

  price_category  
0        gte_226  
1        lte_$75  
2        lte_$75  
3        lte_$75  
4   btw_$75-$150  

[5 rows x 23 columns]

## 3.0 Exploration of the data

In [3]:
# look at the data
airbnb.head(10) 

host_is_superhost  host_identity_verified neighbourhood_cleansed  \
0                  0                       0             Roslindale   
1                  0                       1             Roslindale   
2                  1                       1             Roslindale   
3                  0                       0             Roslindale   
4                  1                       1             Roslindale   
5                  1                       1             Roslindale   
6                  0                       1             Roslindale   
7                  1                       1             Roslindale   
8                  1                       1             Roslindale   
9                  1                       1             Roslindale   

    latitude  longitude property_type        room_type  accommodates  \
0  42.282619 -71.133068         House  Entire home/apt             4   
1  42.286241 -71.134374     Apartment     Private room             2   
2  42.292438 -71.135765     Apartment     Private room             2   
3  42.281106 -71.121021         House     Private room             4   
4  42.284512 -71.136258         House     Private room             2   
5  42.291690 -71.131893   Condominium     Private room             2   
6  42.281390 -71.131190     Apartment  Entire home/apt             3   
7  42.281946 -71.141022         House     Private room             2   
8  42.285878 -71.124910   Condominium     Private room             2   
9  42.288820 -71.139510     Apartment  Entire home/apt             5   

   bathrooms  bedrooms  ...  guests_included price_per_extra_person  \
0        1.5       2.0  ...                1                      0   
1        1.0       1.0  ...                0                      0   
2        1.0       1.0  ...                1                     20   
3        1.0       1.0  ...                2                     25   
4        1.5       1.0  ...                1                      0   
5        1.0       1.0  ...                1                      0   
6        1.0       1.0  ...                1                     25   
7        2.0       1.0  ...                1                     15   
8        1.0       1.0  ...                2                      0   
9        1.0       2.0  ...                4                     25   

   minimum_nights  number_of_reviews  number_days_btw_first_last_review  \
0               2                  0                                  0   
1               2                 36                                804   
2               3                 41                               2574   
3               1                  1                                  0   
4               2                 29                                380   
5               2                  8                                130   
6               1                 57                                421   
7               1                 67                                840   
8               2                 65                                355   
9               4                 33                                876   

   review_scores_rating  cancellation_policy  price  price_gte_150  \
0                   NaN             moderate    250              1   
1                  94.0             moderate     65              0   
2                  98.0             moderate     65              0   
3                 100.0             moderate     75              0   
4                  99.0             flexible     79              0   
5                 100.0             flexible     75              0   
6                  90.0               strict    100              0   
7                  96.0             moderate     75              0   
8                  96.0             moderate     58              0   
9                  94.0               strict    229              1   

  price_category  
0        gte_226  
1        lt

In [4]:
# summary
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3555 entries, 0 to 3554
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   host_is_superhost                  3555 non-null   int64  
 1   host_identity_verified             3555 non-null   int64  
 2   neighbourhood_cleansed             3555 non-null   object 
 3   latitude                           3555 non-null   float64
 4   longitude                          3555 non-null   float64
 5   property_type                      3552 non-null   object 
 6   room_type                          3555 non-null   object 
 7   accommodates                       3555 non-null   int64  
 8   bathrooms                          3541 non-null   float64
 9   bedrooms                           3545 non-null   float64
 10  beds                               3546 non-null   float64
 11  bed_type                           3555 non-null   objec

In [5]:
airbnb.describe()

host_is_superhost  host_identity_verified     latitude    longitude  \
count        3555.000000             3555.000000  3555.000000  3555.000000   
mean            0.113080                0.727989    42.339973   -71.084874   
std             0.316735                0.445058     0.024464     0.031614   
min             0.000000                0.000000    42.235942   -71.171789   
25%             0.000000                0.000000    42.329875   -71.105183   
50%             0.000000                1.000000    42.345191   -71.078487   
75%             0.000000                1.000000    42.354672   -71.062142   
max             1.000000                1.000000    42.389982   -71.000100   

       accommodates    bathrooms     bedrooms         beds  \
count   3555.000000  3541.000000  3545.000000  3546.000000   
mean       3.023629     1.215899     1.246544     1.597293   
std        1.754808     0.492656     0.738440     0.995467   
min        1.000000     0.000000     0.000000     0.000000   
25%        2.000000     1.000000     1.000000     1.000000   
50%        2.000000     1.000000     1.000000     1.000000   
75%        4.000000     1.000000     2.000000     2.000000   
max       16.000000     6.000000     5.000000    16.000000   

       Number of amenities  guests_included  price_per_extra_person  \
count           3555.00000      3555.000000             3555.000000   
mean              14.85879         1.427004               10.886639   
std                4.82126         1.050204               19.092755   
min                0.00000         0.000000                0.000000   
25%               12.00000         1.000000                0.000000   
50%               15.00000         1.000000                0.000000   
75%               18.00000         1.000000               20.000000   
max               30.00000        14.000000              200.000000   

       minimum_nights  number_of_reviews  number_days_btw_first_last_review  \
count     3555.000000        3555.000000                        3555.000000   
mean         3.116737          19.126582                         279.052602   
std          8.273949          35.666178                         408.686952   
min          1.000000           0.000000                           0.000000   
25%          1.000000           1.000000                           0.000000   
50%          2.000000           5.000000                          92.000000   
75%          3.000000          21.000000                         402.000000   
max        300.000000         404.000000                        2680.000000   

       review_scores_rating        price  price_gte_150  
count           2755.000000  3555.000000    3555.000000  
mean              91.891470   166.060478       0.500422  
std                9.548381   103.378456       0.500070  
min               20.000000    10.000000       0.000000  
25%               89.000000    85.000000       0.000000  
50%               94.000000   150.000000       1.000000  
75%               98.000000   219.000000       1.000000  
max              100.000000   650.000000       1.000000

Checking for NAs if any

In [6]:
airbnb.isna().sum()

host_is_superhost                      0
host_identity_verified                 0
neighbourhood_cleansed                 0
latitude                               0
longitude                              0
property_type                          3
room_type                              0
accommodates                           0
bathrooms                             14
bedrooms                              10
beds                                   9
bed_type                               0
Number of amenities                    0
guests_included                        0
price_per_extra_person                 0
minimum_nights                         0
number_of_reviews                      0
number_days_btw_first_last_review      0
review_scores_rating                 800
cancellation_policy                    0
price                                  0
price_gte_150                          0
price_category                         0
dtype: int64

In [6]:
category_var_list = list(airbnb.select_dtypes(include='object').columns)
category_var_list

['neighbourhood_cleansed',
 'property_type',
 'room_type',
 'bed_type',
 'cancellation_policy',
 'price_category']

In [7]:
for cat in category_var_list: # generally, we want to avoid for loops and use a functional style (i.e. list comprehension)
    print(f"Category: {cat} Values: {airbnb[cat].unique()}")

Category: neighbourhood_cleansed Values: ['Roslindale' 'Jamaica Plain' 'Mission Hill' 'Longwood Medical Area'
 'Bay Village' 'Leather District' 'Chinatown' 'North End' 'Roxbury'
 'South End' 'Back Bay' 'East Boston' 'Charlestown' 'West End'
 'Beacon Hill' 'Downtown' 'Fenway' 'Brighton' 'West Roxbury' 'Hyde Park'
 'Mattapan' 'Dorchester' 'South Boston Waterfront' 'South Boston'
 'Allston']
Category: property_type Values: ['House' 'Apartment' 'Condominium' 'Villa' 'Bed & Breakfast' 'Townhouse'
 'Entire Floor' 'Loft' 'Guesthouse' 'Boat' 'Dorm' 'Other' nan 'Camper/RV']
Category: room_type Values: ['Entire home/apt' 'Private room' 'Shared room']
Category: bed_type Values: ['Real Bed' 'Pull-out Sofa' 'Futon' 'Airbed' 'Couch']
Category: cancellation_policy Values: ['moderate' 'flexible' 'strict' 'super_strict_30']
Category: price_category Values: ['gte_226' 'lte_$75' 'btw_$75-$150' 'btw_$151-$225']


## 4.0 Process the data

* Conduct any data prepartion that should be done *BEFORE* the data split.
* Split the data.
* Conduct any data preparation that should be done *AFTER* the data split.

#### Drop any columns/variables we will not be using

In [8]:
# Our target is price; but there are three related price variableds - price, price_gte_150, 
# and price_category. We need to drop price_gte_150, and price_category
airbnb.drop(['price', 'price_category'], axis=1, inplace = True) # keep price_gte_150 for our target

### Encode our categorical variables

In this exercise, we will dummy encode neighbourhood_cleansed, property_type using dummy encoding, and room_type, bed_type and cancelation policy using label encoding.

Before we do our encoding, we must identify if any of our categorical variables have a missing value. We will replace any missing values with the term 'unkown'.

In [9]:
airbnb['property_type'].isna().sum() # check for missing values in this variable/column - we can see there are three for this variable

3

In [10]:
airbnb["property_type"].fillna("unkown", inplace = True)

In [11]:
airbnb['neighbourhood_cleansed'].isna().sum() 

0

In [12]:
airbnb['room_type'].isna().sum() # can see by the results below, no missing values

0

In [13]:
airbnb['bed_type'].isna().sum() # can see by the results below, no missing values

0

In [14]:
airbnb['cancellation_policy'].isna().sum() # can see by the results below, no missing values

0

Now, let's encode neighborhood_cleansed and property_type as dummy variables and room_type, bed_type and cancelation_policy labeled (numeric)

In [15]:
dummies_df = pd.get_dummies(airbnb['neighbourhood_cleansed'], prefix='neighbourhood_cleansed', drop_first=True)

In [16]:
airbnb = airbnb.join(dummies_df)
airbnb.drop('neighbourhood_cleansed', axis=1, inplace = True)

In [17]:
airbnb = airbnb.join(pd.get_dummies(airbnb['property_type'], prefix='property_type', drop_first=True))
airbnb.drop('property_type', axis=1, inplace = True)

In [18]:
labelencoder = LabelEncoder()
airbnb['room_type'] = labelencoder.fit_transform(airbnb['room_type'])
airbnb['bed_type'] = labelencoder.fit_transform(airbnb['bed_type'])
airbnb['cancellation_policy'] = labelencoder.fit_transform(airbnb['cancellation_policy'])

In [19]:
# explore the dataframe columns to verify encoding and dropped columns
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3555 entries, 0 to 3554
Data columns (total 56 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   host_is_superhost                               3555 non-null   int64  
 1   host_identity_verified                          3555 non-null   int64  
 2   latitude                                        3555 non-null   float64
 3   longitude                                       3555 non-null   float64
 4   room_type                                       3555 non-null   int32  
 5   accommodates                                    3555 non-null   int64  
 6   bathrooms                                       3541 non-null   float64
 7   bedrooms                                        3545 non-null   float64
 8   beds                                            3546 non-null   float64
 9   bed_type                                 

### Save the pre-split processed data to a csv file

In [20]:
airbnb.to_csv('airbnb_presplit_processed.csv', index=False)

### 4.2 Split data (train/test)

In [ ]:
# split the data into validation and training set
train_df, test_df = train_test_split(airbnb, test_size=0.3)

# to reduce repetition in later code, create variables to represent the columns
# that are our predictors and target
target = 'price_gte_150'
predictors = list(airbnb.columns)
predictors.remove(target)

In [22]:
numeric_cols_with_nas = list(train_df.isna().sum()[train_df.isna().sum() > 0].index)
numeric_cols_with_nas

['bathrooms', 'bedrooms', 'beds', 'review_scores_rating']

In [23]:
Ns = SimpleImputer(strategy="median")

train_df[numeric_cols_with_nas] = Ns.fit_transform(train_df[numeric_cols_with_nas])
test_df[numeric_cols_with_nas] = Ns.transform(test_df[numeric_cols_with_nas])

#### Standardize numeric values

Now, let's create a common scale between the numberic columns by standardizing each numeric column

In [24]:
# create a standard scaler and fit it to the training set of predictors
scaler = preprocessing.StandardScaler()
cols_to_stdize = ['latitude', 'longitude', 'accommodates', 
                   'bathrooms', 'bedrooms', 'beds', 'Number of amenities', 
                   'guests_included', 'price_per_extra_person', 'minimum_nights', 
                   'number_of_reviews', 'number_days_btw_first_last_review', 
                   'review_scores_rating']                
               
# Transform the predictors of training and validation sets
train_df[cols_to_stdize] = scaler.fit_transform(train_df[cols_to_stdize]) # train_predictors is not a numpy array


test_df[cols_to_stdize] = scaler.transform(test_df[cols_to_stdize]) # validation_target is now a series object


## 5.0 Save the data

In [25]:
train_X = train_df[predictors]
train_y = train_df[target] # train_target is now a series objecttrain_df.to_csv('airbnb_train_df.csv', index=False)
test_X = test_df[predictors]
test_y = test_df[target] # validation_target is now a series object

train_df.to_csv('./data/airbnb_train_df_price_gte_150.csv', index=False)
train_X.to_csv('./data/airbnb_train_X_price_gte_150.csv', index=False)
train_y.to_csv('./data/airbnb_train_y_price_gte_150.csv', index=False)
test_df.to_csv('./data/airbnb_test_df_price_gte_150.csv', index=False)
test_X.to_csv('./data/airbnb_test_X_price_gte_150.csv', index=False)
test_y.to_csv('./data/airbnb_test_y_price_gte_150.csv', index=False)

## Loading the price150 data

In [26]:
X_train = pd.read_csv("./data/airbnb_train_X_price_gte_150.csv")
X_test = pd.read_csv("./data/airbnb_test_X_price_gte_150.csv")
y_train = pd.read_csv("./data/airbnb_train_y_price_gte_150.csv")
y_test = pd.read_csv("./data/airbnb_test_y_price_gte_150.csv")

## 3. Model the data

First, we will create a dataframe to hold all the results of our models.

In [27]:
performance = pd.DataFrame({"model": [], "Accuracy": [], "Precision": [], "Recall": [], "F1": []})

### 3.1 Fit a SVM classification model using linear kernal

In [28]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix



### 3.3 Fit a SVM classification model using polynomial kernal

In [29]:
svm_poly_model = SVC(kernel="poly", degree=3, coef0=1, C=10)
_ = svm_poly_model.fit(X_train, np.ravel(y_train))

In [30]:
model_preds = svm_poly_model.predict(X_test)
c_matrix = confusion_matrix(y_test, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance= pd.concat([performance, pd.DataFrame({'model':"poly svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

In [46]:
performance.sort_values(by=['Precision'],ascending= False)

model  Accuracy  Precision    Recall        F1
0  poly svm  0.867854   0.855839  0.883239  0.869323

## Gridsearch & Decision tree

In [32]:
from sklearn.tree import DecisionTreeClassifier 
from matplotlib import pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

## NOTE: In this next section, GridSearch will use K Fold Cross Validation 

K-Fold cross validation is used to avoid overfitting. 

In k-fold cross-validation, the original sample is randomly partitioned into k equal sized subsamples. Of the k subsamples, a single subsample is retained as the validation data for testing the model, and the remaining k − 1 subsamples are used as training data. The cross-validation process is then repeated k times, with each of the k subsamples used exactly once as the validation data. The k results can then be averaged to produce a single estimation. 

![cross validation diagram](https://scikit-learn.org/stable/_images/grid_search_cross_validation.png)


## Model the data

Conduct an initial random search across a wide range of possible parameters.

In [33]:
score_measure = "precision"
kfolds = 5

param_grid = {
    'min_samples_split': np.arange(1,100),  
    'min_samples_leaf': np.arange(1,100),
    'min_impurity_decrease': np.arange(0.0001, 0.01, 0.0005),
    'max_leaf_nodes': np.arange(5, 100), 
    'max_depth': np.arange(1,55), 
    'criterion': ['entropy', 'gini'],
}


In [34]:

dtree = DecisionTreeClassifier()
rand_search = RandomizedSearchCV(estimator = dtree, param_distributions=param_grid, cv=kfolds, n_iter=300,
                           scoring=score_measure, verbose=1, n_jobs=-1,  # n_jobs=-1 will utilize all available CPUs 
                           return_train_score=True)


In [35]:

_ = rand_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {rand_search.best_score_}")
print(f"... with parameters: {rand_search.best_params_}")

bestRecallTree = rand_search.best_estimator_

Fitting 5 folds for each of 300 candidates, totalling 1500 fits
The best precision score is 0.8530385708950922
... with parameters: {'min_samples_split': 29, 'min_samples_leaf': 23, 'min_impurity_decrease': 0.0031, 'max_leaf_nodes': 44, 'max_depth': 43, 'criterion': 'entropy'}


In [36]:
c_matrix = confusion_matrix(y_test, rand_search.predict(X_test))
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
print(f"Accuracy={(TP+TN)/(TP+TN+FP+FN):.7f} Precision={TP/(TP+FP):.7f} Recall={TP/(TP+FN):.7f} F1={2*TP/(2*TP+FP+FN):.7f}")

Accuracy=0.8462980 Precision=0.8379374 Recall=0.8568738 F1=0.8472998


Conduct an exhaustive search across a smaller range of parameters around the parameters found in the initial random search.

In [ ]:
score_measure = "precision"
kfolds = 5

param_grid = {
    'min_samples_split': np.arange(25,30),  
    'min_samples_leaf': np.arange(15,25),
    'min_impurity_decrease': np.arange(0.0020, 0.0026, 0.0001),
    'max_leaf_nodes': np.arange(85,95), 
    'max_depth': np.arange(25,35), 
    'criterion': ['gini'],
}

dtree = DecisionTreeClassifier()
grid_search = GridSearchCV(estimator = dtree, param_grid=param_grid, cv=kfolds, 
                           scoring=score_measure, verbose=1, n_jobs=-1,  # n_jobs=-1 will utilize all available CPUs 
                           return_train_score=True)

_ = grid_search.fit(X_train, y_train)

print(f"The best {score_measure} score is {grid_search.best_score_}")
print(f"... with parameters: {grid_search.best_params_}")

bestRecallTree = grid_search.best_estimator_

Fitting 5 folds for each of 30000 candidates, totalling 150000 fits


In [38]:
c_matrix = confusion_matrix(y_test, grid_search.predict(X_test))
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
print(f"Accuracy={(TP+TN)/(TP+TN+FP+FN):.7f} Precision={TP/(TP+FP):.7f} Recall={TP/(TP+FN):.7f} F1={2*TP/(2*TP+FP+FN):.7f}")

Accuracy=0.8462980 Precision=0.8379374 Recall=0.8568738 F1=0.8472998


## 5.0 Importance of features

In [39]:
np.round(grid_search.best_estimator_.feature_importances_,2)

array([0.  , 0.  , 0.03, 0.1 , 0.79, 0.  , 0.  , 0.06, 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.02, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

## 6.0 Diagrams of DTrees

In [45]:
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(200,100))
tree = plot_tree(grid_search.best_estimator_, 
              class_names=['< 150', '> 150'], 
              filled=True, 
              rounded=True, 
              fontsize=100)

## SVM Analysis

In conclusion, the poly SVM model has produced the following results. 
* The model's accuracy score of 0.867854 shows that the majority of predictions were accurate. 
* According to the precision of 0.855839, 85.5% of the positive predictions were correct. 
* Recall score of 0.883239, 
* F1 score of 0.869323. 

These findings suggest that, despite the possibility of some false positives and false negatives, the model is highly accurate at predicting positive cases.

## Decison Tree Analysis

* The model achieved an accuracy score of 0.8462980, indicating that it correctly classified 84.6% of the instances in the dataset. 
* The precision score of 0.8379374 suggests that when the model predicted a positive result, it was correct 83.8% of the time. * The recall score of 0.8568738 indicates that the model correctly identified 85.7% of the positive instances in the dataset. * The F1 score of 0.8472998, 

Since the scoring measure is precision, The decison tree performed very well with a precision score of 83.7. Further tuning may increase the value but what we achieved is good!